name: fuzzy-time-gen
version: '0.3.0.0'
category: Time
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2017-2022 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/fuzzy-time
description: Generators for fuzzy-time types

extra-source-files:
- CHANGELOG.md

dependencies:
- base >=4.9 && <=5

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  - fuzzy-time >=0.3
  - genvalidity >=1.0
  - genvalidity-time

tests:
  fuzzy-time-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - fuzzy-time
    - fuzzy-time-gen
    - genvalidity-hspec
    - genvalidity-text
    - hspec
    - megaparsec
    - text
    - time

benchmarks:
  fuzzy-time-bench:
    main: Bench.hs
    source-dirs: bench/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - fuzzy-time
    - fuzzy-time-gen
    - genvalidity-criterion
    - criterion
