name: fuzzy-time
version: 0.2.0.2
category: Time
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2017-2021 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/fuzzy-time
description: Fuzzy time types, parsing and resolution

extra-source-files:
- CHANGELOG.md

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - base >=4.9 && <=5
  - containers
  - deepseq
  - megaparsec
  - text
  - time >=1.9
  - validity
  - validity-time >=0.5
